# Generated by Django 6.0.8 on 2026-08-05 16:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_developerapikey'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='scanlog',
            name='risk_level',
            field=models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High'), ('Critical', 'Critical'), ('Unknown', 'Unknown')], max_length=15),
        ),
        migrations.AlterField(
            model_name='scanlog',
            name='scan_type',
            field=models.CharField(choices=[('TEXT', 'Email/SMS Text'), ('URL', 'URL Link'), ('SCREENSHOT', 'Screenshot OCR'), ('FILE', 'File Upload'), ('PHONE', 'Phone Number')], max_length=20),
        ),
        migrations.AddIndex(
            model_name='scanlog',
            index=models.Index(fields=['user', '-created_at'], name='api_scanlog_user_id_457086_idx'),
        ),
        migrations.AddIndex(
            model_name='scanlog',
            index=models.Index(fields=['-created_at'], name='api_scanlog_created_1ebf51_idx'),
        ),
        migrations.AddIndex(
            model_name='scanlog',
            index=models.Index(fields=['risk_level'], name='api_scanlog_risk_le_9ca993_idx'),
        ),
        migrations.AddIndex(
            model_name='scanlog',
            index=models.Index(fields=['scan_type'], name='api_scanlog_scan_ty_badddc_idx'),
        ),
    ]
