import React, { useState } from 'react';
import { useNavigate, Link } from 'react-router-dom';
import { ShieldAlert, KeyRound, Smartphone, Lock } from 'lucide-react';
import { useAuth } from '../../AuthContext';

export default function AdminLoginPage() {
  const [mode, setMode] = useState('login'); // 'login' | 'request'
  
  // Login State
  const [email, setEmail] = useState('');
  const [authKey, setAuthKey] = useState('');
  
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState('');
  
  const { adminLogin } = useAuth();
  const navigate = useNavigate();

  const handleLoginSubmit = async (e) => {
    e.preventDefault();
    setError('');
    
    if (!email || !authKey) {
      setError('Email and Authentication Key are required.');
      return;
    }
    
    setLoading(true);
    try {
      await adminLogin(email, authKey);
      navigate('/admin');
    } catch (err) {
      setError(err.message || 'Invalid administrator credentials.');
    } finally {
      setLoading(false);
    }
  };

  // The self-service admin registration that used to live here is gone.
  // `/auth/admin-register/` now requires an authenticated administrator — it was
  // AllowAny, so anyone could create a staff account and have the auth key
  // mailed to an address they chose. Provisioning happens in the SOC workspace.

  return (
    <div style={{ display: 'flex', minHeight: '100vh', background: 'var(--bg-primary)', color: 'var(--text-primary)' }}>
      
      {/* Left side: Branding / Warning */}
      <div style={{ flex: 1, display: 'flex', flexDirection: 'column', padding: 64, borderRight: '1px solid var(--border-subtle)', background: 'var(--bg-secondary)', position: 'relative', overflow: 'hidden' }}>
        <div style={{ position: 'absolute', top: '-10%', left: '-10%', width: '50%', height: '50%', background: 'var(--accent-muted)', filter: 'blur(150px)', opacity: 0.5 }}></div>
        
        <div style={{ display: 'flex', alignItems: 'center', gap: 12, marginBottom: 'auto' }}>
          <img src="/logo.png" alt="CyberSentinel" style={{ width: 40, height: 40, objectFit: 'contain' }} />
          <span style={{ fontSize: 24, fontWeight: 800, letterSpacing: '-0.03em' }}>CyberSentinel</span>
        </div>

        <div>
          <div style={{ display: 'flex', alignItems: 'center', gap: 16, marginBottom: 24, color: 'var(--accent-red)' }}>
            <ShieldAlert size={48} />
          </div>
          <h1 style={{ fontSize: 48, fontWeight: 900, lineHeight: 1.1, marginBottom: 24, fontFamily: 'var(--font-sans)', color: 'var(--text-primary)' }}>
            RESTRICTED<br/>SYSTEM ACCESS
          </h1>
          <p style={{ fontSize: 16, color: 'var(--text-secondary)', lineHeight: 1.6, maxWidth: 400 }}>
            You are attempting to access the CyberSentinel Enterprise Control Center. 
            All activity is monitored, logged, and audited. Unauthorized access attempts 
            will be reported to the relevant authorities.
          </p>
        </div>

        {/* This block used to print a fixed IP, a fixed region, and a session ID
            generated by Math.random() on every render — three pieces of security
            telemetry that were pure decoration. The browser cannot know any of
            them; the server records the real values on the login attempt. */}
        <div style={{ marginTop: 'auto', fontSize: 12, color: 'var(--text-muted)', fontFamily: 'var(--font-mono)' }}>
          <div>Sign-in attempts are recorded with their source address and timestamp.</div>
        </div>
      </div>

      {/* Right side: Login Form */}
      <div style={{ flex: 1, display: 'flex', alignItems: 'center', justifyContent: 'center', padding: 64, position: 'relative' }}>
        
        {/* Top Right Actions */}
        <div style={{ position: 'absolute', top: 32, right: 32, display: 'flex', gap: 16 }}>
          <Link to="/" style={{ color: 'var(--text-muted)', fontSize: 14, textDecoration: 'none', fontWeight: 600 }}>&larr; Return to Home</Link>
          <Link to="/login" style={{ color: 'var(--accent)', fontSize: 14, textDecoration: 'none', fontWeight: 600 }}>User Login</Link>
        </div>

        <div style={{ width: '100%', maxWidth: 420 }}>
          
          {mode === 'login' ? (
            <div style={{ animation: 'fadeIn 0.3s' }}>
              <h2 style={{ fontSize: 24, fontWeight: 700, marginBottom: 8 }}>Admin Authentication</h2>
              <p style={{ color: 'var(--text-secondary)', marginBottom: 32, fontSize: 14 }}>Enter your registered email and secure authentication key to proceed.</p>
              
              <form onSubmit={handleLoginSubmit} style={{ display: 'flex', flexDirection: 'column', gap: 20 }}>
                {error && <div role="alert" style={{ padding: 12, background: 'rgba(239,68,68,0.1)', color: 'var(--accent-red)', border: '1px solid rgba(239,68,68,0.2)', borderRadius: 6, fontSize: 13, fontWeight: 600 }}>{error}</div>}
                
                <div>
                  <label htmlFor="admin-email" style={{ display: 'block', fontSize: 12, fontWeight: 700, color: 'var(--text-secondary)', marginBottom: 8, textTransform: 'uppercase' }}>Administrator Email</label>
                  <input 
                    id="admin-email"
                    type="email" 
                    value={email}
                    onChange={e => setEmail(e.target.value)}
                    autoComplete="username"
                    placeholder="admin@cybersentinel.com"
                    style={{ width: '100%', padding: 16, background: 'var(--bg-secondary)', border: '1px solid var(--border-subtle)', borderRadius: 8, color: 'var(--text-primary)', fontSize: 15, outline: 'none', boxShadow: 'var(--shadow-sm)' }}
                  />
                </div>
                
                <div>
                  <label htmlFor="admin-auth-key" style={{ display: 'block', fontSize: 12, fontWeight: 700, color: 'var(--text-secondary)', marginBottom: 8, textTransform: 'uppercase' }}>Authentication Key</label>
                  <input 
                    id="admin-auth-key"
                    type="password" 
                    value={authKey}
                    onChange={e => setAuthKey(e.target.value)}
                    autoComplete="current-password"
                    placeholder="CS-ADMIN-XXXXXXXX"
                    style={{ width: '100%', padding: 16, background: 'var(--bg-secondary)', border: '1px solid var(--border-subtle)', borderRadius: 8, color: 'var(--text-primary)', fontSize: 15, outline: 'none', boxShadow: 'var(--shadow-sm)', fontFamily: 'var(--font-mono)' }}
                  />
                </div>

                <button 
                  type="submit" 
                  disabled={loading}
                  style={{ width: '100%', padding: 16, background: 'var(--text-primary)', color: 'var(--bg-primary)', border: 'none', borderRadius: 8, fontSize: 15, fontWeight: 700, cursor: loading ? 'not-allowed' : 'pointer', marginTop: 8, display: 'flex', alignItems: 'center', justifyContent: 'center', gap: 8 }}
                >
                  {loading ? 'Authenticating...' : <><KeyRound size={18} /> Continue</>}
                </button>
              </form>
              
              <div style={{ display: 'flex', justifyContent: 'space-between', marginTop: 24, fontSize: 13 }}>
                <a href="/login" style={{ color: 'var(--text-muted)', textDecoration: 'none' }}>&larr; Return to Customer Portal</a>
                <button type="button" onClick={() => { setError(''); setMode('request'); }} style={{ background: 'none', border: 'none', color: 'var(--accent)', cursor: 'pointer', fontWeight: 600 }}>Need access?</button>
              </div>
            </div>
          ) : mode === 'request' ? (
            <div style={{ animation: 'fadeIn 0.3s' }}>
              <h2 style={{ fontSize: 24, fontWeight: 700, marginBottom: 8 }}>Requesting admin access</h2>
              <p style={{ color: 'var(--text-secondary)', marginBottom: 24, fontSize: 14, lineHeight: 1.7 }}>
                Administrator accounts are provisioned by an existing administrator, from
                inside the SOC workspace. There is no self-service route, by design:
                anyone who could create their own admin account could read every
                customer's data.
              </p>
              <p style={{ color: 'var(--text-secondary)', marginBottom: 32, fontSize: 14, lineHeight: 1.7 }}>
                Ask a current administrator to add you under <strong>Settings &rarr;
                Administrators</strong>. Your authentication key is emailed to you once
                they do.
              </p>

              <div style={{ display: 'flex', justifyContent: 'center' }}>
                <button
                  type="button"
                  onClick={() => { setError(''); setMode('login'); }}
                  style={{ background: 'none', border: 'none', color: 'var(--text-muted)', fontSize: 13, cursor: 'pointer' }}
                >
                  &larr; Back to sign in
                </button>
              </div>
            </div>
          ) : null}

        </div>
      </div>
    </div>
  );
}
